baseURL = "https://pinguozzo.com"
title = "pinguozzo.com"
theme = "gokarna"
# paginate = 8
pagination.pagerSize = 6

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "music"
    name = "music"
    url = "/music/"
    weight = 2
  [[menu.main]]
    identifier = "lab"
    name = "lab"
    url = "/lab/"
    weight = 3

[params]
  author = "Gianfranco Sigrisi"
  description = "RedHatter inside and Tesla owner. // init7 ref: 85066032124"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/pinguozzo"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/pinguozzo"
  [[params.social]]  
    icon = "linkedin"
    name = "linkedIn"  
    url = "https://linkedin.com/in/gianfrancosigrisi/"

