baseURL = "https://pinguozzo.com.com"
title = "pinguozzo.com"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 3

[params]
  author = "Gianfranco Sigrisi"
  description = "RedHatter inside and Tesla owner. // init7 ref: 85066032124"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/pinguozzo"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/pinguozzo"

