baseURL = "https://gian.sigrisi.ch"
title = "gian.sigrisi.ch"
theme = "gokarna"
# paginate = 8
pagination.pagerSize = 6

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[params]
  author = "Gianfranco Sigrisi"
  description = "RedHatter inside and Tesla owner. // init7 ref: 85066032124"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gsigrisi"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/pinguozzo"
  [[params.social]]  
    icon = "linkedin"
    name = "linkedIn"  
    url = "https://linkedin.com/in/gianfrancosigrisi/"

